name: "first workflow"
on: 
  push:
  pull_request:
    branches:
      - main
      - develop
      - qa
    
jobs: 
    first-job: 
      runs-on: ubuntu-latest
      steps: 
        - name: checkout
          uses: actions/checkout@v4

        - name: setup node js in VM
          uses: actions/setup-node@v4
          with:
            node-version: 24
            cache: npm

        - name: install dependency
          run: npm ci

        - name: run ESLint in app
          run: npm run lint

        - name: make react build
          run: npm run build

        - name: create artifacts
          uses: actions/upload-artifact@v4
          with:
            name: react-build
            path: dist/
            retention-days: 7

